---
- hosts: all
  become: yes
  become_user: root
  tasks:
      - name: ensure mosquitto is at the latest version
        pkgng: pkg=mosquitto state=present
        notify:
            - start mosquitto
  handlers:
      - name: start mosquitto
        service: name=mosquitto state=started
