---
- hosts: all
  become: true
  become_user: root
  gather_facts: False
  
  tasks:
  - name: install python 2
    raw: test -f /usr/bin/python || (pkg install -y python && (ln -sf /usr/local/bin/python /usr/bin/python))
  - setup:
