---
- hosts: all
  become: yes
  become_user: root
  tasks:
      - name: ensure unbound is at the latest version
        apt: pkg=unbound state=latest update_cache=yes
        notify:
            - start unbound
  handlers:
      - name: start unbound
        systemd: name=unbound state=started
