---
- hosts: all
  become: yes
  become_user: root
  tasks:
      - name: ensure mosquitto is at the latest version
        apt: pkg=mosquitto state=latest update_cache=yes
        notify:
            - start mosquitto
  handlers:
      - name: start mosquitto
        service: name=mosquitto state=started
