---
- hosts: all
  become: yes
  become_user: root
  tasks:
      - name: ensure postfix is at the latest version
        apt: pkg=postfix state=present update_cache=yes
        notify:
            - start postfix
  handlers:
      - name: start postfix
        service: name=postfix state=started
