---
- hosts: all
  become: yes
  become_user: root
  tasks:
      - name: ensure bind is at the latest version
        yum: pkg=bind state=latest
        notify:
            - start bind
  handlers:
      - name: start bind
        service: name=named state=started
