---
- hosts: all
  become: yes
  become_user: root
  tasks:
      - name: ensure ntp is at the latest version
        yum: pkg=ntp state=latest
        notify:
            - start ntp
  handlers:
      - name: start ntp
        service: name=ntpd state=started
