---
- hosts: all
  become: yes
  become_user: root
  tasks:
      - name: ensure unbound is at the latest version
        yum: pkg=unbound state=latest
        notify:
            - start unbound
  handlers:
      - name: start unbound
        service: name=unbound state=started
