---
- hosts: all
  become: yes
  become_user: root
  tasks:
      - name: ensure mosquitto is at the latest version
        dnf: pkg=mosquitto state=latest
        notify:
            - start mosquitto
  handlers:
      - name: start mosquitto
        systemd: name=mosquitto state=started
