---
- hosts: all
  become: yes
  become_user: root
  tasks:
      - name: install Extra packages for Enterprise Linux repository
        yum: pkg=epel-release state=present
      - name: ensure mosquitto is at the latest version
        yum: pkg=mosquitto state=latest
        notify:
            - start mosquitto
  handlers:
      - name: start mosquitto
        systemd: name=mosquitto state=started
